# Alpha Rlease of the Final Project

## 1. Color text at the stdout
## 2. Taking user input
## 3. Assert
## 4. Checking legality of move
## 5. Ability to play either side
## 6. Alpha-release of Alak


In [1]:
%matplotlib inline
# All imports

import numpy as np

import sklearn
from sklearn.neural_network import MLPRegressor, MLPClassifier
from sklearn.model_selection import train_test_split

import pickle
np.set_printoptions(formatter={'float': '{:.5f}'.format})


## 1. Color text at the stdout

In [3]:
'''
if necessary:

> conda install -c anaconda colorama

or

> pip install colorama

For more info, see:

https://pypi.python.org/pypi/colorama

'''
from colorama import Fore, Back, Style
print(Fore.RED + 'some red text')
print(Back.GREEN + 'and with a green background')
print(Style.DIM + 'and in dim text')
print(Style.RESET_ALL)

print('back to normal now')


some red text
and with a green background
and in dim text

back to normal now


## 2. Taking user input

In [3]:
mydata = input('Prompt: ')
print(mydata)
print(type(mydata))

Prompt:  awesome


awesome
<class 'str'>


## 3. Assert

In [4]:
# The assert statement
a = 2
assert a == 2 

In [5]:
a = 2
assert a == 3 

AssertionError: 

In [8]:
'''Catching the exception thrown by assert'''
try:
    assert 1 == 2
except:
    print('1 is not equal to 2!')
else:
    print('Everything is fine.')

1 is not equal to 2!


In [5]:
'''
*Part* of my test method -- it's only an example! And not meant to be run!

It's probably not "plug-and-play" depending on how your write your class!

'''

def test_remove(self, verbose=False):
    '''
    The tests include, for both sides:
    - simple kill
    - double kill 
    - double kill that involves more than one piece 
    - suicide moves.
    '''

    board_list = ['xoxoxx____', 'xooxooxx__', '__xoo__oxo', '_xoxxxoo____', '_x_oxxoo____',  '_xoxx___x_']
    board_expect = ['x_x_xx____', 'x__x__xx__', '__xoo__o_o', '_xo___oo____', '_x_o__oo____', '_x_xx___x_']
    off_side = ['x', 'x', 'x', 'o', 'o', 'o']
    fail_num = 0
    print("Testing test_remove after move from offensive side:")
    for i, board in enumerate(board_list):
        print("\nAfter {:s} move:".format(off_side[i]))

        # set board to be the way I want
        self.__init__(board)
        if verbose:
            print("Test {:d}".format(i))
            print('Board: ', self.board)
        self.check_capture(off_side[i], verbose=verbose)
        try:
            assert self.board == board_expect[i]
        except:
            print('i', i)
            fail_num += 1
    tot_num = len(board_list)
    print('{:d} out of {:d} tests passed'.format(len(board_list) - fail_num, len(board_list)))
    if fail_num > 0:
        print(Fore.RED + '{:d} out of {:d} tests failed'.format(fail_num, len(board_list)))


In [9]:
game = Alak(random=True, show_mv=True) #, interactive=True)
game.play()

Starting Game:
Your side is 'o'

round: 0

Board: xxxx__oooo
       0123456789
x : 3 ==> 4
Board: xxx_x_oooo
       0123456789
gain: 0

o : 7 ==> 3
Board: xxxox_o_oo
       0123456789
Suicide move!

Board: xxx_x_o_oo
       0123456789
gain: -1


round: 1

Board: xxx_x_o_oo
       0123456789
x : 4 ==> 7
Board: xxx___oxoo
       0123456789
Suicide move!

Board: xxx___o_oo
       0123456789
gain: -1

o : 8 ==> 5
Board: xxx__oo__o
       0123456789
gain: 0


round: 2

Board: xxx__oo__o
       0123456789
x : 0 ==> 3
Board: _xxx_oo__o
       0123456789
gain: 0

o : 9 ==> 0
Board: oxxx_oo___
       0123456789
gain: 0


round: 3

Board: oxxx_oo___
       0123456789
x : 1 ==> 7
Board: o_xx_oox__
       0123456789
gain: 0

o : 0 ==> 8
Board: __xx_ooxo_
       0123456789
Board: __xx_oo_o_
       0123456789
gain: 1


round: 4

Board: __xx_oo_o_
       0123456789
x : 3 ==> 9
Board: __x__oo_ox
       0123456789
gain: 0

o : 8 ==> 7
Board: __x__ooo_x
       0123456789
gain: 0


round: 5

Board: __x__

In [10]:
game.suicide

True

In [11]:
print(game.X.shape[0], game.y.shape)
print(game.X)
print(game.y)
#x = -1
#o = 1
#_ = 0

16 (16,)
[[-1 -1 -1  0 -1  0  1  1  1  1 -1 -1 -1  0 -1  0  1  0  1  1]
 [-1 -1 -1  0  0  0  1  0  1  1 -1 -1 -1  0  0  1  1  0  0  1]
 [ 0 -1 -1 -1  0  1  1  0  0  1  1 -1 -1 -1  0  1  1  0  0  0]
 [ 1  0 -1 -1  0  1  1 -1  0  0  0  0 -1 -1  0  1  1  0  1  0]
 [ 0  0 -1  0  0  1  1  0  1 -1  0  0 -1  0  0  1  1  1  0 -1]
 [ 0  0  0 -1  0  1  1  1  0 -1  1  0  0 -1  0  0  1  1  0 -1]
 [ 1  0  0  0 -1  0  1  1  0 -1  1  0  0  1 -1  0  0  1  0 -1]
 [ 1  0  0  1 -1  0  0  1 -1  0  1  0  0  0 -1  0  1  1 -1  0]
 [ 1  0 -1  0 -1  0  1  1  0  0  1  0 -1  0 -1  0  0  1  0  0]
 [ 1  0  0  0 -1  0  0  1 -1  0  0  0  0  0 -1  1  0  1 -1  0]
 [ 0  0 -1  0  0  1  0  1 -1  0  1  0 -1  0  0  1  0  0 -1  0]
 [ 1 -1 -1  0  0  1  0  0  0  0  1 -1 -1  0  0  0  0  0  1  0]
 [ 1  0 -1  0  0  0  0 -1  1  0  1  0 -1  0  0  1  0 -1  0  0]
 [ 1  0  0  0 -1  1  0 -1  0  0  1  0  0  0 -1  0  0 -1  1  0]
 [ 1  0  0 -1 -1  0  0  0  1  0  0  0  1 -1 -1  0  0  0  1  0]
 [ 0 -1  0 -1  0  0  0  0  1  0  0 -1  0 -1  0

## You can use np.vstack() to combine the results of many games for 

In [12]:
game.show_mv=True
game.test_remove(verbose=True)

Testing test_remove after move from offensive side:

After x move:
Test 0
Board:  xoxoxx____

After x move:
Test 1
Board:  xooxooxx__

After x move:
Test 2
Board:  __xoo__oxo

After o move:
Test 3
Board:  _xoxxxoo____

After o move:
Test 4
Board:  _x_oxxoo____

After o move:
Test 5
Board:  _xoxx___x_
6 out of 6 tests passed


In [ ]:
game = Alak(interactive=True, random=False, show_mv=True) #, interactive=True)
game.play()

Starting Game:
Your side is 'o'

round: 0

Board: xxxx__oooo
       0123456789
x : 2 ==> 4
Board: xx_xx_oooo
       0123456789
gain: 0

Please enter your move:


Select piece(i): 6
Select position(j): 7


moving 6 ==> 7
illegal move, please try again.
You may select (i): [6 7 8 9]
You may move to (j): [2 5]
Please enter your move:


Select piece(i): 6
Select position(j): 5


moving 6 ==> 5
o : 6 ==> 5
Board: xx_xxo_ooo
       0123456789
gain: 0


round: 1

Board: xx_xxo_ooo
       0123456789
x : 4 ==> 2
Board: xxxx_o_ooo
       0123456789
gain: 0

Please enter your move:


# End of Week15-1